### ISSUE TITLE
Several issues with v2-beta

### ISSUE THREAD

**Issue by xloading** [mapsplugin/v2.0-demo#18]
Hi @wf9a5m75 ,

I'm experiencing multiple issues after updating to v2-beta and would like to hear your advising:
1. For some reason map didn't show within canvas even though MAP_READY event was fired until I have added
```
cordova.fireDocumentEvent('touch_start', {});
```
in MAP_READY handling.
What makes me doubt here is why this is required in my case? I mean in the demo app maps are showing fine without this trick.
Also I have a feeling that this workaround may affect my application generally, see point 3.

2. I have the following code in my application:
```
map.moveCamera({
                  'target': latLngBounds
                }, function () {
                  var cameraPosition = map.getCameraPosition();
                  console.log(cameraPosition);
                  map.setCameraZoom(Math.floor(cameraPosition.zoom - 1));
                  console.log('Camera moved 1');
                });
```
where latLngBounds is array consists of several marker positions and geolocation position (if it is within the radius of specific city). On 1.3.9 master this worked fine and map was bound to this coordinates and a bit zoomed out after this.
With v2-beta this doesn't seem to be the case.

3. I have a feature in my application to choose city of interest ("Change" button in header bar).
However with v2-beta and touch_start trick this doesn't seem to be working anymore, after selecting the city I get the following exception and the app goes unresponsive:
```
Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```
And bottom tabs of application to switch between markers also don't seem to be responsive for some reason.

I have uploaded demo APK to the following path:
https://github.com/xloading/CheapCat/blob/master/android-debug.apk

Please let me know if any additional info is required.

Thank you in advance!

Regards,
Georgy

**Comment by wf9a5m75** [comment]
Hi,

1> Why?

Read this.
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/What-are-news-in-v2%3F#change-4-save-battery-life

The plugin waits approximately 1.5 sec. since the app started.
But if you use splash view or doing other things, the plugin stops watching to save battery life.
You have to this control by yourself .

>2

Screen record (video) please.

>3

Is this mine?
It seems other reasons.
https://www.google.com/search?q=Ignored+attempt+to+cancel+a+touchstart+event+with+cancelable%3Dfalse%2C+for+example+because+scrolling+is+in+progress+and+cannot+be+interrupted.&oq=Ignored+attempt+to+cancel+a+touchstart+event+with+cancelable%3Dfalse%2C+for+example+because+scrolling+is+in+progress+and+cannot+be+interrupted.&aqs=chrome..69i57.375j0j4&sourceid=chrome&ie=UTF-8

**Comment by wf9a5m75** [comment]
> 2

v1.3.9 code (Android)

```java
  @SuppressWarnings("unused")
  private void setZoom(JSONArray args, CallbackContext callbackContext) throws JSONException {
    Long zoom;
    zoom = args.getLong(1);

    this.myMoveCamera(CameraUpdateFactory.zoomTo(zoom), callbackContext);
  }

  private void myMoveCamera(CameraPosition cameraPosition, final CallbackContext callbackContext) {
    CameraUpdate cameraUpdate = CameraUpdateFactory.newCameraPosition(cameraPosition);
    this.myMoveCamera(cameraUpdate, callbackContext);
  }

  private void myMoveCamera(final CameraUpdate cameraUpdate, final CallbackContext callbackContext) {
    map.moveCamera(cameraUpdate);
    callbackContext.success();
  }
```

---

v2.0-beta

```java
  public void setCameraZoom(JSONArray args, final CallbackContext callbackContext) throws JSONException {
    final Long zoom = args.getLong(0);
    this.activity.runOnUiThread(new Runnable() {
      @Override
      public void run() {
        myMoveCamera(CameraUpdateFactory.zoomTo(zoom), callbackContext);
      }
    });
  }

  public void myMoveCamera(CameraPosition cameraPosition, final CallbackContext callbackContext) {
    final CameraUpdate cameraUpdate = CameraUpdateFactory.newCameraPosition(cameraPosition);
    this.activity.runOnUiThread(new Runnable() {
      @Override
      public void run() {
        myMoveCamera(cameraUpdate, callbackContext);
      }
    });
  }

  public void myMoveCamera(CameraUpdate cameraUpdate, CallbackContext callbackContext) {
    try {
        map.moveCamera(cameraUpdate);
    } catch (Exception e) {
        e.printStackTrace();
    }
    callbackContext.success();
  }
```

Actually I didn't change anything about the `map.setCameraZoom()` method.

**Comment by xloading** [comment]
Hi @wf9a5m75 ,

Thank you a lot for quick answers, I will need to look deeper into these Android problems and will get back to you asap.
Meanwhile could you please have a quick look and possibly share any ideas why iOS app with v2-beta and the same JS code as the Android apk provided yesterday is absolutely irresponsive?
Here is the screencast:
https://youtu.be/KtVnysS7c8w

Thank you once again!

**Comment by wf9a5m75** [comment]
Could you share the project source code?

**Comment by xloading** [comment]
@wf9a5m75, sorry for delay, uploaded it here:
https://github.com/xloading/guidelance_mapv2

**Comment by wf9a5m75** [comment]
Sorry, but I'm not familiar with ionic. Could you tell me how to build you project?

I build you project, but I got JS errors.
![screen shot 2016-11-12 at 7 27 00 pm](https://cloud.githubusercontent.com/assets/167831/20243487/364c3454-a90e-11e6-9113-ba11c9ee963a.png)

**Comment by xloading** [comment]
@wf9a5m75, I have included all the dependencies into bower.json and plugins into config.xml plus some minor fixes into index.html.
You now need to do update from my repo, run **bower install**, and it is also better to remove and re-add iOS platform to cordova.

Apologies for inconvenience, this was my personal project before and I didn't need to restore it from Git earlier.

Thank you!

**Comment by wf9a5m75** [comment]
Ok, I could build your project, but I could not find out where is start position.
And it seems you are trying to use the v1 code.

`Map.getMap()` returns the same instance in v1, but the method returns different instances always in v2.

I recommend you write your code from scratch.

**Comment by xloading** [comment]
@wf9a5m75 , thank you for the prompt feedback.
I have found one minor issue on backend API code preventing your location from being properly processed. And also for the convenience of your debug added Los Angeles and one it's sightseeing to the backend database. 
Regarding start position if you mean how the map code is invoked on home screen, then the stack is following:
```
controllers.js -> mainCtrl
$ionicPlatform.ready fired
LocationUIService.showConfirm(position);
MapService.homeMap(position, $rootScope.tempLocation.id);
```

And speaking about different instances created by Map.getMap() I will need to think about that and probably re-write the code as you advised but I would be thankful if you could explain why the application is irresponsive on home screen even though there are no multiple getMap() calls (I only use single call in MapService._homeMap() in services.js and then re-use **map** variable).

Thanks!

**Comment by wf9a5m75** [comment]
Ok, thank you for the hint. I finally see the map on Android.
`$cordovaGeolocation.getCurrentPosition(options)` does not work on my Android for some reason.
So I provide the dummy position.

Anyway, I figured out why your application is irresponsive.
Since you use v1 code, your code runs `Map.getMap()` method on the same div.
In this case, (as I describe before) the plugin returns different instances.
It means the plugin creates new map in native side.
So that's why the plugin confuses, and your app becomes irresponsive.
However, I updated the plugin code to prevent this issue.
The plugin returns the same instance if the div is already recognized as map div.

And regarding of the touchstart does not work, the plugin internal calculates is incorrect.
I fixed it.

Please reinstall the maps plugin, and it should work with your app **on Android**
https://dl.dropboxusercontent.com/u/1456061/tmp/guidelance_mapv2.apk

-----

I will check the ios from now.

**Comment by xloading** [comment]
Hi @wf9a5m75 ,

Thank you indeed for the fixes, I'm at the moment fighting with my environment to rebuild the app properly and will give latest version a try.

While I'm working on this could you please have a look at two more things that make life with v2-beta much more complicated:

- Download size of plugin from #multiple-maps branch is enormous - I've looked at git-remote-https process network stats and it reports ~150-160Mb download for main plugin and ~50Mb more for ios-specific part. As Github is somehow limiting cloning speed each plugin installation takes 15-20 minutes each time on my side :(
Is it correct in terms of traffic as I don't see anything taking that much space after plugin installation?

- I remember your answer on the problem with
```
There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-googlemaps.
The conflicting plugin, undefined, already modified the same attributes.
```
but I have investigated that further on my side and couldn't find in other plugins any edit-config section and android:largeHeap doesn't seem to be present anywhere else.
Could you please give a try to investigate this further as it bothers a lot as well?

Thank you once again Masashi!

**Comment by wf9a5m75** [comment]
> Downloading is so slow.

The easy & faster way is install the plugin from local.

```
$> mkdir work_dir
$> cd work_dir

$ work_dir > git clone https://github.com/mapsplugin/cordova-plugin-googlemaps
$ work_dir > cd cordova-plugin-googlemaps
$ cordova-plugin-googlemaps > git checkout multiple_maps
$ cordova-plugin-googlemaps > cd ../../

$ work_dir > git clone https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk
$ work_dir > cd cordova-plugin-googlemaps-sdk
$ cordova-plugin-googlemaps-sdk > git checkout 2.1.1   // <--- if you want
$ cordova-plugin-googlemaps-sdk > cd ..

$ work_dir > cordova create HelloMap ... (etc) . // or create your project with ionic
$ work_dir > cd HelloMap
$ HelloMap > cordova plugin add ../cordova-plugin-googlemaps-sdk
$ HelloMap > cordova plugin add ../cordova-plugin-googlemaps --variable API_KEY_......
```

I guess the cordova-cli command uses javascript version of git command.
That's why so slow (I guess).

------

Regarding of the ` <edit-config>`, it should be written in the AndroidManifest.xml (final generated file).
I don't know how the ionic handle this one internally.

**Comment by wf9a5m75** [comment]
@xloading Did you solve you issues?

**Comment by xloading** [comment]
Hi Masashi,

Thank you indeed for the hint with cloning repo locally - it worked like a charm!

I'm still testing the latest version with fixes on Android, main issue left there is the strange behavior of moveCamera() on the startup - will investigate this deeper and provide some feedback by tomorrow EOD.

But iOS still continues to be fully irresponsive for me. Did you have a chance to check my project code with iOS?

**Comment by xloading** [comment]
Hi @wf9a5m75 ,

After further testing I continue to experience two major issues on Android:
1. On application startup map is not initiated even though I have 
```
cordova.fireDocumentEvent('touch_start', {});
```
in my code.

2. moveCamera and setCameraZoom in the following piece of code don't behave as in v1:
```
var latLngBounds = new plugin.google.maps.LatLngBounds($rootScope.latLng);

              if($rootScope.latLng.length > 0) {
                console.log('Before camera moved 1');
                console.log(latLngBounds);
                map.moveCamera({
                  'target': latLngBounds
                }, function () {
                  var cameraPosition = map.getCameraPosition();
                  console.log(cameraPosition);
                  map.setCameraZoom(Math.floor(cameraPosition.zoom - 1));
                  console.log('Camera moved 1');
                });
              }
```
i.e. no scaling to LatLngBounds happens and auto zoom out after that.

I have uploaded screencast to youtube:
https://youtu.be/Ncg9v2dkyUw

**Comment by wf9a5m75** [comment]
1. You need to modify like this:

https://github.com/xloading/guidelance_mapv2/blob/5c4116d64ae45e36b99b5f4b5253e1bef26aa2b6/www/js/controllers.js#L30-L42
```js
//$cordovaGeolocation.getCurrentPosition(options).then(function (position) {

  Location.query({}, function (data) {
    $rootScope.locations = data;
  });

  //$rootScope.position = position;
  var position = {
    coords: {
      latitude: 0,
      longitude: 0
    }
  };

  LocationUIService.showConfirm(position);

}, function (error) {
  console.log("Could not get location");
});
//});
```

$cordovaGeolocation.getCurrentPosition does not work always (at least for me at all)

----

2. inspecting.

**Comment by xloading** [comment]
Hi @wf9a5m75 ,

Regarding your problem with geolocation - this is strange, because it is working absolutely fine for me on both iOS and Android emulators and devices that I have.

Are you sure you have cordova-plugin-geolocation installed for the project?
Could you please run **cordova plugins** to check this?

**Comment by xloading** [comment]
@wf9a5m75, any news on the problems with Android moveCamera() and iOS irresponsiveness?

**Comment by wf9a5m75** [comment]
Regarding of the ios does not work at all, the criminal is the `cordova-plugin-statusbar` plugin.
The statusbar plugin inserts a dummy view in front of the browser.
That's why the plugin can not detect the touch view correctly.

If you remove the status bar plugin, the plugin works fine.

**Comment by wf9a5m75** [comment]
Ah, @Hirbod notes as **Important notice**. You have to execute `StatusBar.overlaysWebView(false)`
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map#important-notice

**Comment by wf9a5m75** [comment]
After fighting with the `cordova-plugin-statusbar`, I figured out a solution.
So the plugin (should) work with the statusbar plugin.
You don't need to do anything for your code.

Just reinstall the latest plugin code.

**Comment by Hirbod** [comment]
The status bar plugin inserts a dummy view for being able to fetch the "status bar tap", which usually will scroll the webview back to top.

**Comment by xloading** [comment]
Hi @wf9a5m75 ,

Your latest fixes worked like a charm - currently I have no issues with iOS at all.
How did you debug that to status bar? You're doing amazing job and I would love to learn the proper ways to investigate such problems in the future and possibly help you with some issues.

Do you have any ideas on Android moveCamera() with LatLngBounds issue? I've tried to debug this call through Android Studio but I don't have much experience with Java and plugin's code looked rather complicated to me therefore I cannot come to any conclusion yet.

Thank you indeed!
